# Generated by Django 3.2.9 on 2021-12-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerid', models.CharField(db_column='customerID', max_length=50, primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='userName', max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('firstname', models.CharField(db_column='firstName', max_length=50)),
                ('lastname', models.CharField(db_column='lastName', max_length=50)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Customer',
                'managed': False,
            },
        ),
    ]
