# Generated by Django 3.2.9 on 2021-12-29 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cartid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('totalpayment', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
            ],
            options={
                'db_table': 'cart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cartitem',
            fields=[
                ('cartitemid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cartitem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('categoryname', models.CharField(blank=True, max_length=20, null=True)),
                ('totalpercategory', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orderitem',
            fields=[
                ('orderitemid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orderitem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orderlist',
            fields=[
                ('orderid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('recievername', models.CharField(blank=True, max_length=150, null=True)),
                ('recieverphone', models.CharField(blank=True, max_length=20, null=True)),
                ('recieveraddress', models.CharField(blank=True, max_length=300, null=True)),
                ('orderdate', models.DateTimeField(blank=True, null=True)),
                ('totalpayment', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('orderstatus', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'orderlist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paymentdetail',
            fields=[
                ('paymentid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('paymenttype', models.CharField(blank=True, max_length=20, null=True)),
                ('transactiontime', models.DateTimeField(blank=True, null=True)),
                ('paymentstatus', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'paymentdetail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('productname', models.CharField(blank=True, max_length=50, null=True)),
                ('productdesc', models.CharField(blank=True, max_length=300, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productsize',
            fields=[
                ('sizeid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('productsize', models.CharField(blank=True, max_length=5, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'productsize',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reviewid',
            fields=[
                ('reviewid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('rating', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('note', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'reviewid',
                'managed': False,
            },
        ),
    ]
