# Generated by Django 3.2.9 on 2021-12-22 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211222_0931'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
